# Generated by Django 4.2.20 on 2025-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('standing', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('starting_year', models.IntegerField()),
                ('total_attendance', models.IntegerField(default=0)),
                ('last_attendance_time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='student_images/')),
            ],
        ),
    ]
